# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Singapore Beach Ultimate
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
    Website of Singapore Beach Ultimate, regular pick-up games information,
    team training and information abotu hosted beach ultimate tournaments.
baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://sgbu.github.io" # the base hostname & protocol for your site
url: "http://localhost:3000"

include: ["_pages", "_team", "_tournaments"]

# twitter_username: jekyllrb
github_username:  sgbu
telegram:   SGBeachUltimate
facebook:   156245137744553

# Build settings
markdown: kramdown
